name: kiosk_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.0.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Margherita-pizza.jpg
    - assets/images/Spaghetti-Carbonara.jpg
    - assets/images/Lasagna.jpg
    - assets/images/Risotto-alla-Milanese.jpg
    - assets/images/Fettuccine-Alfredo.jpg
    - assets/images/Penne-Arrabbiata.jpg
    - assets/images/Gnocchi-Sorrentina.jpg
    - assets/images/Osso-Buco.jpg
    - assets/images/Eggplant-Parmigiana.jpg
    - assets/images/Esspresso.jpg
    - assets/images/Cappuccino.jpg
    - assets/images/Italian soda.jpg
    - assets/images/Red wine.jpg
    - assets/images/Tiramisu.jpg
    - assets/images/Cannoli.jpg
    - assets/images/Panna-Cotta.jpg
    - assets/images/Gelato.jpg
    - assets/images/Sfogliatella.jpg
    - assets/images/Zeppole.jpg
    